name: Deno build test and push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
    contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

    #   - name: Run linter
    #     run: deno lint

      - name: Setup silverbullet
        run: deno install -f --name silverbullet  --unstable-kv --unstable-worker-options -A https://get.silverbullet.md
    
      - name: Add Deno bin to PATH
        run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $PATH

      - name: Silverbullet version
        run: silverbullet --version

      - name: Run Deno build task
        run: deno task build-release

      - name: Commit and push if on main
        # TODO: remove
        # if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add silverbullet-ai.plug.js
          git commit -m "Auto update silverbullet-ai.plug.js"
          git push