name: Deno Build and Commit

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: latest

      - name: Run Deno build task
        run: deno task build-release

      - name: Commit and push if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add silverbullet-ai.plug.js
          git commit -m "Auto update silverbullet-ai.plug.js"
          git push