name: Deno build test and push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
    contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@fa660b328d065f7683e7303976bd81e2d58e98ae # v1.4.1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check
      
      - name: Run Deno test
        run: deno task test
      
      - name: Coverage
        run: deno coverage --lcov cov_profile/ > cov.lcov

    #   - name: Run linter
    #     run: deno lint

      - name: Setup silverbullet
        run: deno install -f --name silverbullet  --unstable-kv --unstable-worker-options -A https://get.silverbullet.md
    
      - name: Add Deno bin to PATH
        run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $PATH

      - name: Silverbullet version
        run: silverbullet --version

      - name: Run Deno build task
        run: deno task build-release

      - name: Commit and push if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add silverbullet-ai.plug.js || true
          git commit -m "Auto update silverbullet-ai.plug.js [skip ci]" || true
          git push